services:
  api:
    build: .
    container_name: chat_pdf_ai
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./tmp:/app/tmp
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
